import { getSupabaseClient } from '@/template';
import { FunctionsHttpError } from '@supabase/supabase-js';
import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as AppleAuthentication from 'expo-apple-authentication';
import * as Crypto from 'expo-crypto';
import {
  GoogleSignin,
  isSuccessResponse,
  isErrorWithCode,
  statusCodes,
} from '@react-native-google-signin/google-signin';
import { User } from './types';

const supabase = getSupabaseClient();

// Thrown when the user dismisses the native Apple/Google sheet — never a
// real error, callers must swallow it silently (no alert).
export class AuthCancelledError extends Error {
  constructor() {
    super('SIGN_IN_CANCELLED');
    this.name = 'AuthCancelledError';
  }
}

function mapAuthUserToUser(authUser: any, profile?: any): User {
  return {
    id: authUser.id,
    email: authUser.email || '',
    name:
      profile?.username ||
      authUser.user_metadata?.username ||
      authUser.user_metadata?.name ||
      authUser.user_metadata?.full_name ||
      authUser.email?.split('@')[0] ||
      'Usuário',
    plan: profile?.plan || 'free',
    createdAt: authUser.created_at,
  };
}

let googleConfigured = false;
function ensureGoogleConfigured() {
  if (googleConfigured) return;
  GoogleSignin.configure({
    webClientId: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID,
    iosClientId: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID,
    scopes: ['profile', 'email'],
    offlineAccess: false, // no serverAuthCode needed — Supabase only wants the idToken
  });
  googleConfigured = true;
}

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
}

// Apple: pass the SHA-256 HASH to signInAsync, the RAW string to Supabase.
// Apple echoes the value we give it verbatim into the token's nonce claim;
// Supabase hashes whatever nonce we pass it and compares against that
// claim. Swapping raw/hashed is the #1 cause of "invalid nonce" failures.
async function makeNoncePair() {
  const rawNonce = toHex(Crypto.getRandomBytes(32));
  const hashedNonce = await Crypto.digestStringAsync(
    Crypto.CryptoDigestAlgorithm.SHA256,
    rawNonce,
  );
  return { rawNonce, hashedNonce };
}

const PENDING_APPLE_NAME_KEY = '@spinshot:pending_apple_name';

async function stashPendingAppleName(name: string) {
  try {
    await AsyncStorage.setItem(PENDING_APPLE_NAME_KEY, name);
  } catch {}
}

// Apple only ever sends fullName on the very FIRST authorization of this
// app by that Apple ID — never again, not even after uninstall/reinstall.
// We stash it locally the moment it arrives (stashPendingAppleName, called
// before any await that could fail) and apply it here. Guarded so a first
// Apple auth that lands on an account which already has a real username
// (auto-linked by email, or set by the user) doesn't clobber it.
async function applyPendingAppleName(authUser: any) {
  let profile = await getUserProfileSafe(authUser.id);

  let pending: string | null = null;
  try {
    pending = await AsyncStorage.getItem(PENDING_APPLE_NAME_KEY);
  } catch {}
  if (!pending) return profile;

  const emailLocalPart = authUser.email?.split('@')[0] ?? '';
  const current = (profile?.username ?? '').trim();
  const looksAutoGenerated = !current || current === emailLocalPart;

  if (!looksAutoGenerated) {
    try { await AsyncStorage.removeItem(PENDING_APPLE_NAME_KEY); } catch {}
    return profile;
  }

  const { error } = await supabase.auth.updateUser({
    data: { username: pending, name: pending, full_name: pending },
  });

  if (!error) {
    try { await AsyncStorage.removeItem(PENDING_APPLE_NAME_KEY); } catch {}
    profile = await getUserProfileSafe(authUser.id); // re-read: sync_user_metadata() just ran
  }
  // On error, leave the stash in place — retried on the next successful sign-in.

  return profile;
}

async function getUserProfileSafe(userId: string): Promise<any | null> {
  try {
    const { data, error } = await supabase
      .from('user_profiles')
      .select('*')
      .eq('id', userId)
      .maybeSingle();

    if (error) {
      console.warn('[authService] profile lookup failed:', error.message);
      return null;
    }

    return data ?? null;
  } catch (error: any) {
    console.warn('[authService] profile lookup exception:', error?.message || error);
    return null;
  }
}

export const authService = {
  async login(email: string, password: string): Promise<User> {
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (error) {
      throw new Error(error.message);
    }

    if (!data.user) {
      throw new Error('Usuário não retornado no login');
    }

    const profile = await getUserProfileSafe(data.user.id);

    return mapAuthUserToUser(data.user, profile);
  },

  async register(
    name: string,
    email: string,
    password: string
  ): Promise<{ user: User; needsEmailConfirmation: boolean }> {
    const { data, error } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: { username: name, name },
      },
    });

    if (error) {
      throw new Error(error.message);
    }

    if (!data.user) {
      throw new Error('Erro ao criar conta');
    }

    const user = mapAuthUserToUser(data.user, {
      username: name,
      plan: 'free',
    });

    if (data.session) {
      return {
        user,
        needsEmailConfirmation: false,
      };
    }

    return {
      user,
      needsEmailConfirmation: true,
    };
  },

  async getStoredUser(): Promise<User | null> {
    const {
      data: { session },
      error,
    } = await supabase.auth.getSession();

    if (error) {
      throw new Error(error.message);
    }

    if (!session?.user) {
      return null;
    }

    const profile = await getUserProfileSafe(session.user.id);

    return mapAuthUserToUser(session.user, profile);
  },

  async signInWithGoogle(): Promise<User> {
    ensureGoogleConfigured();

    if (Platform.OS === 'android') {
      await GoogleSignin.hasPlayServices({ showPlayServicesUpdateDialog: true });
    }

    let response;
    try {
      response = await GoogleSignin.signIn();
    } catch (e: any) {
      if (isErrorWithCode(e) && e.code === statusCodes.SIGN_IN_CANCELLED) {
        throw new AuthCancelledError();
      }
      throw new Error(e?.message || 'Google Sign-In failed');
    }

    // v13+ returns a discriminated union instead of throwing on cancel.
    if (!isSuccessResponse(response)) {
      throw new AuthCancelledError();
    }

    const idToken = response.data.idToken;
    if (!idToken) {
      throw new Error('Google did not return an ID token');
    }

    const { data, error } = await supabase.auth.signInWithIdToken({
      provider: 'google',
      token: idToken,
    });
    if (error) throw new Error(error.message);
    if (!data.user) throw new Error('Usuário não retornado no login');

    const profile = await getUserProfileSafe(data.user.id);
    return mapAuthUserToUser(data.user, profile);
  },

  async signInWithApple(): Promise<User> {
    const available = await AppleAuthentication.isAvailableAsync();
    if (!available) {
      throw new Error('Sign in with Apple não está disponível neste dispositivo');
    }

    const { rawNonce, hashedNonce } = await makeNoncePair();

    let credential: AppleAuthentication.AppleAuthenticationCredential;
    try {
      credential = await AppleAuthentication.signInAsync({
        requestedScopes: [
          AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
          AppleAuthentication.AppleAuthenticationScope.EMAIL,
        ],
        nonce: hashedNonce,
      });
    } catch (e: any) {
      if (e?.code === 'ERR_REQUEST_CANCELED') throw new AuthCancelledError();
      throw new Error(e?.message || 'Sign in with Apple failed');
    }

    if (!credential.identityToken) {
      throw new Error('Apple did not return an identity token');
    }

    // Capture the name BEFORE any await that could fail — Apple only ever
    // sends it once, on the very first authorization.
    const appleName = [credential.fullName?.givenName, credential.fullName?.familyName]
      .filter(Boolean)
      .join(' ')
      .trim();
    if (appleName) await stashPendingAppleName(appleName);

    const { data, error } = await supabase.auth.signInWithIdToken({
      provider: 'apple',
      token: credential.identityToken,
      nonce: rawNonce,
    });
    if (error) throw new Error(error.message);
    if (!data.user) throw new Error('Usuário não retornado no login');

    const profile = await applyPendingAppleName(data.user);
    return mapAuthUserToUser(data.user, profile);
  },

  async logout(): Promise<void> {
    try {
      ensureGoogleConfigured();
      if (GoogleSignin.hasPreviousSignIn()) {
        await GoogleSignin.signOut();
      }
    } catch (e) {
      // Never block the real sign-out over Google's local cache cleanup.
      console.warn('[authService] google signOut failed', e);
    }

    const { error } = await supabase.auth.signOut();
    if (error) {
      throw new Error(error.message);
    }
  },

  async deleteAccount(): Promise<void> {
    const {
      data: { session },
      error: sessionError,
    } = await supabase.auth.getSession();

    if (sessionError) {
      throw new Error(sessionError.message);
    }

    if (!session?.user) {
      throw new Error('Usuário não autenticado');
    }

    const userId = session.user.id;

    // Best-effort — revoga o acesso do Google antes de excluir a conta,
    // mesmo padrão non-blocking do logout() acima.
    try {
      ensureGoogleConfigured();
      if (GoogleSignin.hasPreviousSignIn()) {
        await GoogleSignin.revokeAccess();
      }
    } catch (e) {
      console.warn('[authService] google revokeAccess failed', e);
    }

    // Best-effort cleanup de arquivos antes da exclusão do usuário
    const buckets: Array<{ bucket: string; limit: number }> = [
      { bucket: 'spinshot-videos', limit: 200 },
      { bucket: 'spinshot-logos',  limit: 100 },
      { bucket: 'spinshot-frames', limit: 100 },
    ];

    for (const { bucket, limit } of buckets) {
      try {
        const { data: files } = await supabase.storage.from(bucket).list(userId, { limit });
        if (files?.length) {
          await supabase.storage.from(bucket).remove(files.map((f) => `${userId}/${f.name}`));
        }
      } catch (e) {
        console.warn(`[deleteAccount] failed to remove files from ${bucket}`, e);
      }
    }

    // Apple exige revogar o token na exclusão de conta (guideline 5.1.1(v))
    // pra quem usou Sign in with Apple. A Apple só reemite um authorization
    // code num sign-in novo — precisamos pedir um fresco agora mesmo, na
    // hora do delete. Best-effort: se o usuário cancelar a folha ou algo
    // falhar, a exclusão segue normalmente sem revogação.
    let appleAuthorizationCode: string | null = null;
    const hasAppleIdentity = session.user.identities?.some((i: any) => i.provider === 'apple');
    if (hasAppleIdentity && Platform.OS === 'ios') {
      try {
        const available = await AppleAuthentication.isAvailableAsync();
        if (available) {
          const credential = await AppleAuthentication.signInAsync({ requestedScopes: [] });
          appleAuthorizationCode = credential.authorizationCode ?? null;
        }
      } catch (e) {
        console.warn('[authService] could not get fresh Apple authorization code for revoke', e);
      }
    }

    // Chama a Edge Function via SDK (garante URL e auth corretos automaticamente)
    const { error: fnError } = await supabase.functions.invoke('delete-account', {
      body: { appleAuthorizationCode },
    });

    if (fnError) {
      let msg = fnError.message ?? 'Erro ao excluir conta';
      if (fnError instanceof FunctionsHttpError) {
        try {
          const text = await fnError.context?.text();
          if (text) msg = text;
        } catch {}
      }
      throw new Error(msg);
    }

    // Limpa sessão local após exclusão bem-sucedida
    await supabase.auth.signOut();
  },

  async upgradeToPro(_userId: string): Promise<User> {
    const current = await authService.getStoredUser();
    if (!current) {
      throw new Error('Usuário não encontrado');
    }

    return { ...current, plan: 'pro' };
  },
};
